# Generated by Django 5.2.6 on 2025-09-09 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Akun',
            fields=[
                ('kode_akun', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nama_akun', models.CharField(max_length=255)),
                ('tipe_akun', models.CharField(choices=[('Aset', 'Aset'), ('Liabilitas', 'Liabilitas'), ('Ekuitas', 'Ekuitas'), ('Pendapatan', 'Pendapatan'), ('Beban', 'Beban'), ('Akumulasi Penyusutan', 'Akumulasi Penyusutan'), ('Harga Pokok Penjualan', 'Harga Pokok Penjualan')], max_length=50)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='buku_besar.akun')),
            ],
            options={
                'ordering': ['kode_akun'],
            },
        ),
    ]
