# Generated by Django 5.2.6 on 2025-09-10 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JurnalUmum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_transaksi', models.CharField(blank=True, editable=False, max_length=25, unique=True)),
                ('tanggal', models.DateField()),
                ('deskripsi', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-tanggal', '-nomor_transaksi'],
            },
        ),
        migrations.CreateModel(
            name='Akun',
            fields=[
                ('kode_akun', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nama_akun', models.CharField(max_length=255)),
                ('tipe_akun', models.CharField(choices=[('Kas & Bank', 'Kas & Bank'), ('Piutang Usaha', 'Piutang Usaha'), ('Persediaan', 'Persediaan'), ('Aset Lancar Lainnya', 'Aset Lancar Lainnya'), ('Aset Tetap', 'Aset Tetap'), ('Akumulasi Penyusutan', 'Akumulasi Penyusutan'), ('Utang Usaha', 'Utang Usaha'), ('Liabilitas Jangka Pendek', 'Liabilitas Jangka Pendek'), ('Liabilitas Jangka Panjang', 'Liabilitas Jangka Panjang'), ('Modal', 'Modal'), ('Pendapatan', 'Pendapatan'), ('Harga Pokok Penjualan', 'Harga Pokok Penjualan'), ('Beban', 'Beban'), ('Pendapatan lainnya', 'Pendapatan lainnya'), ('Beban lainnya', 'Beban lainnya')], max_length=50)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('saldo_awal', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('tanggal_saldo_awal', models.DateField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='buku_besar.akun')),
            ],
            options={
                'ordering': ['kode_akun'],
            },
        ),
        migrations.CreateModel(
            name='JurnalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('kredit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='buku_besar.akun')),
                ('jurnal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='buku_besar.jurnalumum')),
            ],
        ),
    ]
