# Generated by Django 5.2.6 on 2025-09-09 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buku_besar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='akun',
            name='saldo_awal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='akun',
            name='tanggal_saldo_awal',
            field=models.DateField(blank=True, null=True),
        ),
    ]
