# Generated by Django 5.2.6 on 2025-09-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buku_besar', '0002_akun_saldo_awal_akun_tanggal_saldo_awal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akun',
            name='tipe_akun',
            field=models.CharField(choices=[('Kas & Bank', 'Kas & Bank'), ('Piutang Usaha', 'Piutang Usaha'), ('Persediaan', 'Persediaan'), ('Aset Lancar Lainnya', 'Aset Lancar Lainnya'), ('Aset Tetap', 'Aset Tetap'), ('Akumulasi Penyusutan', 'Akumulasi Penyusutan'), ('Utang Usaha', 'Utang Usaha'), ('Modal', 'Modal'), ('Pendapatan', 'Pendapatan'), ('Harga Pokok Penjualan', 'Harga Pokok Penjualan'), ('Beban', 'Beban'), ('Pendapatan lainnya', 'Pendapatan lainnya'), ('Beban lainnya', 'Beban lainnya')], max_length=50),
        ),
    ]
